# Site settings
title: "Margarida Pinto 2022 resume"
description: "From jglovier"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Margarida Pinto"
resume_title:                   "Neuroscience PhD student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "anamargaridampinto@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       "555-7334"
#resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "<small>46 Rue d'Ulm, 75005 Paris FR </small> • anamargaridampinto@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: PhD student at École Normale Supérieure. Interviewer for <a href="https://www.storiesofwin.org/">Stories of Women in Neuroscience</a>. Passionate about movement, orientation, learning and locomotion.

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
#resume_section_links:           false
#resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/anamargaridampinto"
  resume_twitter_url:           "http://twitter.com/margarida_m_p"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/margarida-pinto-635240204/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
